In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
import numpy as np

from error_prop import propagazione_errore


frac = lambda val: propagazione_errore(["a", "b"] , "a/b" , val , [[np.sqrt(val[0]) , 0] , [0 , np.sqrt(val[1])]] , Display=False)

## Note

- Nei grafici gli errori sono a caso
- Mancano i fattori geometrici

In [2]:
default_dir = str(Path(".").absolute()).split("/Lab-muons")[0]+"/Lab-muons/"
universal_dir = lambda path: default_dir + path

DATA_PATH = universal_dir("Data/calibration/dead_zones.csv")
SIM_PATH = universal_dir("simulazioni/bolde/muons/muon_distribution_simulation_results.csv")

data = pd.read_csv(DATA_PATH, sep=",", header=0)
sim = pd.read_csv(SIM_PATH , sep=",", header=0)
display(data)
display(sim)

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
0,mpg,0,0,0,9321,7198,5882,NaN,5784,5.0
1,mpg,15,0,0,9478,6597,5907,NaN,4995,5.0
2,mpg,30,0,0,9288,5363,5877,NaN,3743,5.0
3,mpg,45,0,0,9194,4068,5908,NaN,2503,5.0
4,mpg,60,0,0,9472,2761,6146,NaN,1468,5.0
5,mpg,75,0,0,9597,1402,5896,NaN,362,5.0
6,mgp,0,0,0,9405,5926,7188,NaN,5787,5.0
7,mgp,0,15,0,9300,5992,6504,NaN,4996,5.0
8,mgp,0,30,0,9370,6024,5371,NaN,3755,5.0
9,mgp,0,45,0,9127,5954,4039,NaN,2540,5.0
10,mgp,0,60,0,9440,6074,2632,NaN,1418,5.0
11,mgp,0,75,0,9554,6082,1231,NaN,323,5.0
12,gmp,0,0,0,9179,0,6029,4189.0,4104,NaN
13,gmp,0,0,15,8800,0,5752,4294.0,3871,NaN
14,gmp,0,0,30,9197,0,4074,4093.0,2668,NaN
15,gmp,0,0,45,8212,0,2707,3839.0,1546,NaN
16,gmp,0,0,60,8285,0,1527,3773.0,710,NaN
17,gmp,0,0,75,8108,0,550,3961.0,118,NaN

,configuration,Tx,Ty,Tz,Mx,My,Mz,Bx,By,Bz,doppie,triple,flag
0,m g p,0,0,12.8,0,0,8.4,0,0,0,100000,100000,184026
1,m g p,0,0,12.8,15,0,8.4,0,0,0,100000,85475,205206
2,m g p,0,0,12.8,30,0,8.4,0,0,0,100000,65248,230556
3,m g p,0,0,12.8,45,0,8.4,0,0,0,100000,44966,258704
4,m g p,0,0,12.8,60,0,8.4,0,0,0,100000,24718,285885
5,m g p,0,0,12.8,75,0,8.4,0,0,0,100000,4661,312010
6,g m p,0,0,23.0,0,0,12.8,0,0,0,100000,100000,304441
7,g m p,0,0,23.0,15,0,12.8,0,0,0,100000,86424,322253
8,g m p,0,0,23.0,30,0,12.8,0,0,0,100000,65456,355339
9,g m p,0,0,23.0,45,0,12.8,0,0,0,100000,43566,390869
10,g m p,0,0,23.0,60,0,12.8,0,0,0,100000,21704,423219
11,g m p,0,0,23.0,75,0,12.8,0,0,0,100000,2439,456235
12,g m p,0,0,25.3,0,0,12.8,0,0,0,100000,100000,339351
13,g m p,0,0,25.3,15,0,12.8,0,0,0,100000,87053,358741
14,g m p,0,0,25.3,30,0,12.8,0,0,0,100000,65637,394256
15,g m p,0,0,25.3,45,0,12.8,0,0,0,100000,43618,430776
16,g m p,0,0,25.3,60,0,12.8,0,0,0,100000,21407,465910
17,g m p,0,0,25.3,75,0,12.8,0,0,0,100000,2331,503306

In [3]:
df_P = data[data['ordine[TtB]'] == 'mpg']
df_G = data[data['ordine[TtB]'] == 'mgp']
df_M = data[data['ordine[TtB]'] == 'gmp']

display( df_P)

,ordine[TtB],p_distanza[cm],g_distanza[cm],m_distanza[cm],p_count,pm_doppie,gm_doppie,pg_doppie,pgm_triple,tempo[min]
0,mpg,0,0,0,9321,7198,5882,NaN,5784,5.0
1,mpg,15,0,0,9478,6597,5907,NaN,4995,5.0
2,mpg,30,0,0,9288,5363,5877,NaN,3743,5.0
3,mpg,45,0,0,9194,4068,5908,NaN,2503,5.0
4,mpg,60,0,0,9472,2761,6146,NaN,1468,5.0
5,mpg,75,0,0,9597,1402,5896,NaN,362,5.0

# Misure

In [4]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = df_P['p_distanza[cm]'] , y = ((df_P[' pgm_triple'])/(df_P[' gm_doppie'])) , mode = 'markers' , name = 'p_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_P['p_distanza[cm]']) , visible = True)))


fig.add_trace( go.Scatter( x = df_G['g_distanza[cm]'] , y = ((df_G[' pgm_triple'])/(df_G[' pm_doppie'])) , mode = 'markers' , name = 'g_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_G['g_distanza[cm]']) , visible = True)))

fig.add_trace( go.Scatter( x = df_M['m_distanza[cm]'] , y = ((df_M[' pgm_triple'])/(df_M[' pg_doppie'])) , mode = 'markers' , name = 'g_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(df_M['m_distanza[cm]']) , visible = True)))


fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

# Simulazione

In [5]:
sim_P = sim[sim['configuration'] == 'm g p']
sim_G = sim[sim['configuration'] == 'm g p']
sim_M = sim[sim['configuration'] == 'g m p']

sim_M_1 = sim_M[sim_M['Tz'] == 23.0]
sim_M_2 = sim_M[sim_M['Tz'] == 25.3]

display(sim_P)
display(sim_M_1)

  configuration  Tx  Ty    Tz  Mx  My   Mz  Bx  By  Bz  doppie  triple    flag
0         m g p   0   0  12.8   0   0  8.4   0   0   0  100000  100000  184026
1         m g p   0   0  12.8  15   0  8.4   0   0   0  100000   85475  205206
2         m g p   0   0  12.8  30   0  8.4   0   0   0  100000   65248  230556
3         m g p   0   0  12.8  45   0  8.4   0   0   0  100000   44966  258704
4         m g p   0   0  12.8  60   0  8.4   0   0   0  100000   24718  285885
5         m g p   0   0  12.8  75   0  8.4   0   0   0  100000    4661  312010

,configuration,Tx,Ty,Tz,Mx,My,Mz,Bx,By,Bz,doppie,triple,flag
6,g m p,0,0,23.0,0,0,12.8,0,0,0,100000,100000,304441
7,g m p,0,0,23.0,15,0,12.8,0,0,0,100000,86424,322253
8,g m p,0,0,23.0,30,0,12.8,0,0,0,100000,65456,355339
9,g m p,0,0,23.0,45,0,12.8,0,0,0,100000,43566,390869
10,g m p,0,0,23.0,60,0,12.8,0,0,0,100000,21704,423219
11,g m p,0,0,23.0,75,0,12.8,0,0,0,100000,2439,456235

In [6]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_P['Mx'] , y = ((sim_P['triple'])/(sim_P['doppie'])) , mode = 'markers' , name = 'p_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_P['Mx']) , visible = True)))


fig.add_trace( go.Scatter( x = sim_M['Mx'] , y = ((sim_M['triple'])/(sim_M['doppie'])) , mode = 'markers' , name = 'M_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_M['Mx']) , visible = True)))

fig.add_trace( go.Scatter( x = sim_G['Mx'] , y = ((sim_G['triple'])/(sim_G['doppie'])) , mode = 'markers' , name = 'g_sim_efficiency' , error_y = dict( type='data' , array=0.1*np.ones_like(sim_G['Mx']) , visible = True)))


fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

# Partenope

In [7]:
tP_S = np.array(sim_P['triple'])
dP_S = np.array(sim_P['doppie'])
tP = np.array(df_P[' pgm_triple'])
dP = np.array(df_P[' gm_doppie'])

err_data = [float(frac([tP[i], dP[i]])) for i in range(len(tP))]
err_sim = [float(frac([tP_S[i], dP_S[i]])) for i in range(len(tP_S))]

fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_P['Mx'] , y = ((sim_P['triple'])/(sim_P['doppie'])) , mode = 'markers' , name = 'P' , error_y = dict( type='data' , array=err_sim , visible = True)))

fig.add_trace( go.Scatter( x = df_P['p_distanza[cm]'] , y = ((df_P[' pgm_triple'])/(df_P[' gm_doppie'])) , mode = 'markers' , name = 'P_data' , error_y = dict( type='data' , array=err_data , visible = True)))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

## diff

In [8]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_P['Mx'] , y = -((df_P[' pgm_triple'])/(df_P[' gm_doppie']) - (sim_P['triple'].to_numpy())/(sim_P['doppie'].to_numpy())) , mode = 'markers' , name = 'P'))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'diff sim-data')
fig.show()

# Giunone

In [9]:
tG_S = np.array(sim_G['triple'])
dG_S = np.array(sim_G['doppie'])
tG = np.array(df_G[' pgm_triple'])
dG = np.array(df_G[' pm_doppie'])

err_data = [ float(frac([tG[i], dG[i]])) for i in range(len(tG))]
err_sim = [ float(frac([tG_S[i], dG_S[i]])) for i in range(len(tG_S))]

fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_G['Mx'] , y = ((sim_G['triple'])/(sim_G['doppie'])) , mode = 'markers' , name = 'G' , error_y = dict( type='data' , array=err_sim, visible = True)))

fig.add_trace( go.Scatter( x = df_G['g_distanza[cm]'] , y = ((df_G[' pgm_triple'])/(df_G[' pm_doppie'])) , mode = 'markers' , name = 'G_data' , error_y = dict( type='data' , array=err_data , visible = True)))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

## Diff

In [10]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_G['Mx'] , y = -(((df_G[' pgm_triple'])/(df_G[' pm_doppie'])) - ((sim_G['triple'].to_numpy())/(sim_G['doppie'].to_numpy()))) , mode = 'markers' , name = 'G'))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'diff sim-data')
fig.show()

# Minerva

In [11]:
tM_S = np.array(sim_M['triple'])
dM_S = np.array(sim_M['doppie'])
tM = np.array(df_M[' pgm_triple'])
dM = np.array(df_M[' pg_doppie'])

err_data = [ float(frac([tM[i], dM[i]])) for i in range(len(tM))]
err_sim = [ float(frac([tM_S[i], dM_S[i]])) for i in range(len(tM_S))]

err_sim1 = err_sim[:len(sim_M_1["Mx"]):]
err_sim2 = err_sim[len(sim_M_1["Mx"])::]

fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_M_1['Mx'] , y = ((sim_M_1['triple'])/(sim_M_1['doppie'])) , mode = 'markers' , name = 'M1' , error_y = dict( type='data' , array=err_sim1 , visible = True)))

fig.add_trace( go.Scatter( x = sim_M_2['Mx'] , y = ((sim_M_2['triple'])/(sim_M_2['doppie'])) , mode = 'markers' , name = 'M2' , error_y = dict( type='data' , array=err_sim2 , visible = True)))

fig.add_trace( go.Scatter( x = df_M['m_distanza[cm]'] , y = ((df_M[' pgm_triple'])/(df_M[' pg_doppie'])) , mode = 'markers' , name = 'M_data' , error_y = dict( type='data' , array=err_data , visible = True)))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'rate triple/doppie')
fig.show()

## Diff

In [12]:
fig = go.Figure()

fig.add_trace( go.Scatter( x = sim_M_1['Mx'] , y = -((df_M[' pgm_triple'])/(df_M[' pg_doppie']) - (sim_M_1['triple'].to_numpy())/(sim_M_1['doppie'].to_numpy())) , mode = 'markers' , name = 'M1'))

fig.add_trace( go.Scatter( x = sim_M_2['Mx'] , y = -((df_M[' pgm_triple'])/(df_M[' pg_doppie']) - (sim_M_2['triple'].to_numpy())/(sim_M_2['doppie'].to_numpy())) , mode = 'markers' , name = 'M2'))

fig.update_xaxes( title_text = 'distanza[cm]')
fig.update_yaxes( title_text = 'diff sim-data')
fig.show()